"""scas_upgrade

Revision ID: 76bfec6ad2c3
Revises: 65e0203b5218
Create Date: 2026-06-03 17:28:43.567345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bfec6ad2c3'
down_revision: Union[str, None] = '65e0203b5218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.Enum('medical', 'ta_da', 'other', name='claimtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'processed', name='claimstatus'), nullable=False),
    sa.Column('documents', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_employee_id'), 'claims', ['employee_id'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('education_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'defaulted', name='loanstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_loans_id'), 'education_loans', ['id'], unique=False)
    op.create_index(op.f('ix_education_loans_student_id'), 'education_loans', ['student_id'], unique=False)
    op.create_table('noc_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='nocstatus'), nullable=False),
    sa.Column('library_dues', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hostel_dues', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_dues', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noc_requests_id'), 'noc_requests', ['id'], unique=False)
    op.create_index(op.f('ix_noc_requests_student_id'), 'noc_requests', ['student_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('refund_type', sa.Enum('caution_money', 'excess_fee', 'course_withdrawal', name='refundtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'processed', name='refundstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_student_id'), 'refunds', ['student_id'], unique=False)
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', name='salarystatus'), nullable=False),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salaries_employee_id'), 'salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_approved', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='scholarshipstatus'), nullable=False),
    sa.Column('documents_url', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_student_id'), 'scholarships', ['student_id'], unique=False)
    op.create_table('loan_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'received', 'delayed', name='installmentstatus'), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['education_loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_installments_id'), 'loan_installments', ['id'], unique=False)
    op.create_index(op.f('ix_loan_installments_loan_id'), 'loan_installments', ['loan_id'], unique=False)
    op.add_column('college_settings', sa.Column('late_fee_type', sa.String(length=50), nullable=False))
    op.add_column('college_settings', sa.Column('late_fee_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('college_settings', sa.Column('late_fee_slabs', sa.String(length=1000), nullable=True))
    op.add_column('fee_structures', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('student_fees', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_locked')
    op.drop_column('students', 'hashed_password')
    op.drop_column('student_fees', 'due_date')
    op.drop_column('fee_structures', 'due_date')
    op.drop_column('college_settings', 'late_fee_slabs')
    op.drop_column('college_settings', 'late_fee_amount')
    op.drop_column('college_settings', 'late_fee_type')
    op.drop_index(op.f('ix_loan_installments_loan_id'), table_name='loan_installments')
    op.drop_index(op.f('ix_loan_installments_id'), table_name='loan_installments')
    op.drop_table('loan_installments')
    op.drop_index(op.f('ix_scholarships_student_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_employee_id'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_index(op.f('ix_refunds_student_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_noc_requests_student_id'), table_name='noc_requests')
    op.drop_index(op.f('ix_noc_requests_id'), table_name='noc_requests')
    op.drop_table('noc_requests')
    op.drop_index(op.f('ix_education_loans_student_id'), table_name='education_loans')
    op.drop_index(op.f('ix_education_loans_id'), table_name='education_loans')
    op.drop_table('education_loans')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_employee_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
